version: "3.8"

services:
  mongo1:
    image: mongo:4.0.4
    container_name: mongo1
    environment:
     - MONGO_DATA_DIR=/data/db
     - MONGO_LOG_DIR=/dev/null
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=admin
    #extra_hosts:
    #- "mongo2:"<IP of vm2>"
    volumes:
      - ./data/dbdata:/data/db
      - ./keyauth:/data/keyauth
    ports:
      - 27017:27017
    command: mongod --port 27017 --keyFile /data/keyauth --dbpath /data/db --replSet rs0 --bind_ip 0.0.0.0
   # command: mongod  --port 27017 --bind_ip 0.0.0.0
    #network_mode: host
